# Generated by Django 5.2.4 on 2025-07-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bracket_name", models.CharField(max_length=100)),
                ("img", models.CharField(max_length=1000)),
                ("amount_of_stages", models.CharField(max_length=10)),
                (
                    "bracket_creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bracket_object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obj_name", models.CharField(max_length=100)),
                ("stage", models.CharField(max_length=10)),
                ("img", models.CharField(max_length=1000)),
                (
                    "bracket_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to="bracket.bracket",
                    ),
                ),
            ],
        ),
    ]
