# Generated by Django 5.2.4 on 2025-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0004_bracket_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket",
            name="amount_of_stages",
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name="bracket_object",
            name="stage",
            field=models.IntegerField(default=32),
        ),
    ]
