# Generated by Django 5.2.4 on 2025-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bracket",
            "0006_bracket_object_is_left_side_bracket_object_slot_col_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket_object",
            name="slot_col",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="bracket_object",
            name="slot_row",
            field=models.FloatField(default=1),
        ),
    ]
