# Generated by Django 5.2.4 on 2025-07-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bracket",
            "0008_rename_amount_of_stages_bracket_amount_of_participants_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket_object",
            name="bracket_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brack_name",
                to="bracket.bracket",
            ),
        ),
        migrations.CreateModel(
            name="Participant_stages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semi_final", models.BooleanField(default=False)),
                ("final", models.BooleanField(default=False)),
                (
                    "bracket_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="br_name",
                        to="bracket.bracket",
                    ),
                ),
                (
                    "obj_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="br_obj_name",
                        to="bracket.bracket_object",
                    ),
                ),
            ],
        ),
    ]
