# Generated by Django 5.2.4 on 2025-07-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0010_remove_participant_stages_obj_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant_stages",
            name="obj_name",
        ),
        migrations.AddField(
            model_name="participant_stages",
            name="obj_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bracket.bracket_object",
            ),
        ),
    ]
