# Generated by Django 5.2.4 on 2025-07-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0011_remove_participant_stages_obj_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bracket_object",
            old_name="slot_col",
            new_name="slot_row_final",
        ),
        migrations.RenameField(
            model_name="bracket_object",
            old_name="slot_row",
            new_name="slot_row_semi",
        ),
    ]
