# Generated by Django 5.2.4 on 2025-08-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0014_participant_stages_quater_final"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bracket_object",
            name="slot_row_final",
        ),
    ]
