# Generated by Django 5.2.4 on 2025-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0016_bracket_object_semi_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant_stages",
            name="one_eigth",
            field=models.BooleanField(default=False),
        ),
    ]
