# Generated by Django 5.2.4 on 2025-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0018_rename_one_eigth_participant_stages_one_eight"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket_object",
            name="quater_coords",
            field=models.FloatField(default=1),
        ),
    ]
