# Generated by Django 5.2.4 on 2025-08-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0022_groupparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
