# Generated by Django 5.2.4 on 2025-08-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0024_bracket_object_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bracket_object",
            name="group",
        ),
    ]
