# Generated by Django 5.2.5 on 2025-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0025_remove_bracket_object_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_stages',
            name='final_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant_stages',
            name='semi_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant_stages',
            name='winner_winner',
            field=models.BooleanField(default=False),
        ),
    ]
