# Generated by Django 5.2.5 on 2025-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0026_participant_stages_final_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_stages',
            name='quater_winner',
            field=models.BooleanField(default=False),
        ),
    ]
