# Generated by Django 5.2.4 on 2025-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0002_bracket_bracket_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket",
            name="amount_of_stages",
            field=models.ImageField(default=32, upload_to=""),
        ),
        migrations.AlterField(
            model_name="bracket_object",
            name="stage",
            field=models.ImageField(default=32, upload_to=""),
        ),
    ]
