# Generated by Django 5.2.4 on 2025-07-22 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0003_alter_bracket_amount_of_stages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
