# Generated by Django 5.2.4 on 2025-07-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0005_alter_bracket_amount_of_stages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket_object",
            name="is_left_side",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bracket_object",
            name="slot_col",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bracket_object",
            name="slot_row",
            field=models.IntegerField(default=1),
        ),
    ]
