# Generated by Django 5.2.4 on 2025-07-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0007_alter_bracket_object_slot_col_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bracket",
            old_name="amount_of_stages",
            new_name="amount_of_participants",
        ),
        migrations.RemoveField(
            model_name="bracket_object",
            name="stage",
        ),
        migrations.AddField(
            model_name="bracket_object",
            name="current_stage",
            field=models.CharField(default="semi-final", max_length=20),
        ),
    ]
