# Generated by Django 5.2.4 on 2025-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0009_alter_bracket_object_bracket_name_participant_stages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant_stages",
            name="obj_name",
        ),
        migrations.AddField(
            model_name="participant_stages",
            name="obj_name",
            field=models.ManyToManyField(to="bracket.bracket_object"),
        ),
    ]
