# Generated by Django 5.2.4 on 2025-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0012_rename_slot_col_bracket_object_slot_row_final_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket_object",
            name="video_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
