# Generated by Django 5.2.4 on 2025-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0013_bracket_object_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant_stages",
            name="quater_final",
            field=models.BooleanField(default=False),
        ),
    ]
