# Generated by Django 5.2.4 on 2025-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0015_remove_bracket_object_slot_row_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket_object",
            name="semi_coords",
            field=models.FloatField(default=1),
        ),
    ]
