# Generated by Django 5.2.4 on 2025-08-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0017_participant_stages_one_eigth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant_stages",
            old_name="one_eigth",
            new_name="one_eight",
        ),
    ]
