# Generated by Django 5.2.4 on 2025-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0019_bracket_object_quater_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="brack_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
