# Generated by Django 5.2.4 on 2025-08-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0021_bracket_object_user_participant_stages_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_position", models.IntegerField()),
                ("is_winner", models.BooleanField(default=False)),
                (
                    "bracket_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bracket.bracket",
                    ),
                ),
                (
                    "obj_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bracket.bracket_object",
                    ),
                ),
            ],
        ),
    ]
