# Generated by Django 5.2.4 on 2025-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0023_groupparticipant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket_object",
            name="group",
            field=models.IntegerField(null=True),
        ),
    ]
