# Generated by Django 5.2.7 on 2025-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0027_participant_stages_quater_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket_object',
            name='current_stage',
            field=models.CharField(db_index=True, default='semi-final', max_length=20),
        ),
    ]
